# pasted in the skeleton

# This is a basic workflow to package the udaconnect project
name: "udaconnect - Package with Docker"

# Trigger the workflow on push to the main branch
on:
  push:
    branches: [ main ]

  # Also run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push api
        uses: docker/build-push-action@v2
        with:
          context: ./modules/api
          file: ./modules/api/Dockerfile
          platforms: linux/amd64
          push: true
          tags: naturallyunintelligent/udaconnect-api:latest

      -
        name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: ./modules/frontend
          file: ./modules/frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: naturallyunintelligent/udaconnect-app:latest
